"""
Atlas AI Trading Platform

Signal Model

Represents a complete trading signal.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime


@dataclass(slots=True)
class Signal:
    """
    Trading signal generated by a strategy.
    """

    # Instrument
    symbol: str = ""

    # BUY / SELL / HOLD
    action: str = "HOLD"

    # LONG / SHORT
    direction: str = "LONG"

    # Strategy information
    strategy: str = "Atlas Strategy"

    timeframe: str = ""

    # Signal quality
    confidence: float = 0.0

    score: int = 0

    # Trade levels
    entry: float = 0.0

    stop_loss: float = 0.0

    take_profit: float = 0.0

    # Risk management
    risk_reward: float = 0.0

    position_size: int = 0

    # Why the signal exists
    reason: str = ""

    ai_summary: str = ""

    # Lifecycle
    created: datetime = field(
        default_factory=datetime.now
    )

    valid: bool = True

    executed: bool = False

    def invalidate(self) -> None:
        """
        Mark the signal as invalid.
        """

        self.valid = False

    def execute(self) -> None:
        """
        Mark the signal as executed.
        """

        self.executed = True

    @property
    def tradable(self) -> bool:
        """
        Can this signal be traded?
        """

        return (

            self.valid

            and

            self.action != "HOLD"

            and

            self.confidence >= 70

        )

    def summary(self) -> dict:
        """
        Dictionary representation.
        """

        return {

            "symbol": self.symbol,

            "action": self.action,

            "direction": self.direction,

            "strategy": self.strategy,

            "confidence": self.confidence,

            "score": self.score,

            "entry": self.entry,

            "stop_loss": self.stop_loss,

            "take_profit": self.take_profit,

            "risk_reward": self.risk_reward,

            "position_size": self.position_size,

            "tradable": self.tradable,

        }

    def __str__(self):

        return (

            f"{self.symbol} "

            f"{self.action} "

            f"({self.confidence:.1f}%)"

        )